# StackAPI

#### Import the necessary libraries here:

In [1]:
import sys
from pandas.io.json import json_normalize

In [2]:
# your code here
import json
import requests
import pandas as pd
import stackapi
from stackapi import StackAPI
import datetime

#### Question 1: Find the questions and answers of last month.

In [3]:
# your code here
SITE = StackAPI('stackoverflow')
comments = SITE.fetch('comments')
# Does not work when I add 'fromdate=datetime(2019,7,10), todate=datetime(2019,7,11)' after comments

data = pd.DataFrame(comments)
print(data)

     backoff  has_more  page  quota_max  quota_remaining  total  \
0          0      True     5        300              300      0
1          0      True     5        300              300      0
2          0      True     5        300              300      0
3          0      True     5        300              300      0
4          0      True     5        300              300      0
5          0      True     5        300              300      0
6          0      True     5        300              300      0
7          0      True     5        300              300      0
8          0      True     5        300              300      0
9          0      True     5        300              300      0
10         0      True     5        300              300      0
11         0      True     5        300              300      0
12         0      True     5        300              300      0
13         0      True     5        300              300      0
14         0      True     5        300              300      0
15         0      True     5        300              300      0
16         0      True     5        300              300      0
17         0      True     5        300              300      0
18         0      True     5        300              300      0
19         0      True     5        300              300      0
20         0      True     5        300              300      0
21         0      True     5        300              300      0
22         0      True     5        300              300      0
23         0      True     5        300              300      0
24         0      True     5        300              300      0
25         0      True     5        300              300      0
26         0      True     5        300              300      0
27         0      True     5        300              300      0
28         0      True     5        300              300      0
29         0      True     5        300              300      0
..       ...       ...   ...        ...              ...    ...
470        0      True     5        300              300      0
471        0      True     5        300              300      0
472        0      True     5        300              300      0
473        0      True     5        300              300      0
474        0      True     5        300              300      0
475        0      True     5        300              300      0
476        0      True     5        300              300      0
477        0      True     5        300              300      0
478        0      True     5        300              300      0
479        0      True     5        300              300      0
480        0      True     5        300              300      0
481        0      True     5        300              300      0
482        0      True     5        300              300      0
483        0      True     5        300              300      0
484        0      True     5        300              300      0
485        0      True     5        300              300      0
486        0      True     5        300              300      0
487        0      True     5        300              300      0
488        0      True     5        300              300      0
489        0      True     5        300              300      0
490        0      True     5        300              300      0
491        0      True     5        300              300      0
492        0      True     5        300              300      0
493        0      True     5        300              300      0
494        0      True     5        300              300      0
495        0      True     5        300              300      0
496        0      True     5        300              300      0
497        0      True     5        300              300      0
498        0      True     5        300              300      0
499        0      True     5        300              300      0

                                                 items
0    {'owner': {'reputation': 1, 'user_id': 1122538...
1    {'owner': {'reputation': 68, 'user_id': 569474...
2    {'owner': {'reputation': 28468, 'user_id': 391...
3    {'owner': {'reputation': 138, 'user_id': 55494...
4    {'owner': {'reputation': 1, 'user_id': 1167809...
5    {'owner': {'reputation': 1, 'user_id': 1117090...
6    {'owner': {'reputation': 3, 'user_id': 1180524...
7    {'owner': {'reputation': 417, 'user_id': 75236...
8    {'owner': {'reputation': 835737, 'user_id': 11...
9    {'owner': {'reputation': 36, 'user_id': 117251...
10   {'owner': {'reputation': 748202, 'user_id': 10...
11   {'owner': {'reputation': 321, 'user_id': 10989...
12   {'owner': {'reputation': 1635, 'user_id': 1038...
13   {'owner': {'reputation': 765, 'user_id': 11363...
14   {'owner': {'reputation': 70616, 'user_id': 163...
15   {'owner': {'reputation': 20780, 'user_id': 281...
16   {'owner': {'reputation': 1, 'user_id': 1178550...
17   {'owner': {'reputation': 4, 'user_id': 1176055...
18   {'owner': {'reputation': 15634, 'user_id': 711...
19   {'owner': {'reputation': 3, 'user_id': 1049496...
20   {'owner': {'reputation': 1051, 'user_id': 3370...
21   {'owner': {'reputation': 606, 'user_id': 21108...
22   {'owner': {'reputation': 24860, 'user_id': 448...
23   {'owner': {'reputation': 6, 'user_id': 3433923...
24   {'owner': {'reputation': 1, 'user_id': 1160459...
25   {'owner': {'reputation': 117, 'user_id': 31428...
26   {'owner': {'reputation': 42826, 'user_id': 298...
27   {'owner': {'reputation': 7887, 'user_id': 2145...
28   {'owner': {'reputation': 32789, 'user_id': 178...
29   {'owner': {'reputation': 477, 'user_id': 21389...
..                                                 ...
470  {'owner': {'reputation': 306, 'user_id': 32359...
471  {'owner': {'reputation': 19965, 'user_id': 318...
472  {'owner': {'reputation': 676933, 'user_id': 19...
473  {'owner': {'reputation': 373, 'user_id': 43763...
474  {'owner': {'reputation': 1, 'user_id': 1180475...
475  {'owner': {'reputation': 2249, 'user_id': 2731...
476  {'owner': {'reputation': 10469, 'user_id': 399...
477  {'owner': {'reputation': 1, 'user_id': 8774724...
478  {'owner': {'reputation': 15721, 'user_id': 148...
479  {'owner': {'reputation': 20, 'user_id': 117591...
480  {'owner': {'reputation': 863, 'user_id': 47790...
481  {'owner': {'reputation': 4113, 'user_id': 6933...
482  {'owner': {'reputation': 15695, 'user_id': 220...
483  {'owner': {'reputation': 175, 'user_id': 76463...
484  {'owner': {'reputation': 6, 'user_id': 1162978...
485  {'owner': {'reputation': 445, 'user_id': 80364...
486  {'owner': {'reputation': 20707, 'user_id': 516...
487  {'owner': {'reputation': 1336, 'user_id': 4458...
488  {'owner': {'reputation': 54, 'user_id': 116113...
489  {'owner': {'reputation': 759, 'user_id': 31977...
490  {'owner': {'reputation': 1084, 'user_id': 1889...
491  {'owner': {'reputation': 90, 'user_id': 837314...
492  {'owner': {'reputation': 31083, 'user_id': 909...
493  {'owner': {'reputation': 68, 'user_id': 107174...
494  {'owner': {'reputation': 107, 'user_id': 52444...
495  {'owner': {'reputation': 8570, 'user_id': 5025...
496  {'owner': {'reputation': 592, 'user_id': 45977...
497  {'owner': {'reputation': 2722, 'user_id': 1592...
498  {'owner': {'reputation': 54, 'user_id': 116113...
499  {'owner': {'reputation': 8525, 'user_id': 2413...

[500 rows x 7 columns]

In [4]:
def flatten (data, col_list):
    for column in col_list:
        flattened = pd.DataFrame(dict(data[column])).transpose()
        columns = [str(col) for col in flattened.columns]
        flattened.columns = [column + '_' + colname for colname in columns]
        data = pd.concat([data, flattened], axis=1)
        data = data.drop(column, axis=1)
    return data

nested_columns = ['items']

flat = flatten(data, nested_columns)
flat

,backoff,has_more,page,quota_max,quota_remaining,total,items_comment_id,items_creation_date,items_edited,items_owner,items_post_id,items_reply_to_user,items_score
0,0,True,5,300,300,0,100808537,1563800803,False,"{'reputation': 1, 'user_id': 11225383, 'user_t...",57146630,NaN,0
1,0,True,5,300,300,0,100808536,1563800803,False,"{'reputation': 68, 'user_id': 5694740, 'user_t...",54700076,NaN,0
2,0,True,5,300,300,0,100808535,1563800801,False,"{'reputation': 28468, 'user_id': 3915431, 'use...",57145644,NaN,0
3,0,True,5,300,300,0,100808534,1563800800,False,"{'reputation': 138, 'user_id': 5549431, 'user_...",57119783,"{'reputation': 325, 'user_id': 10012519, 'user...",0
4,0,True,5,300,300,0,100808533,1563800791,False,"{'reputation': 1, 'user_id': 11678098, 'user_t...",57102174,NaN,0
5,0,True,5,300,300,0,100808532,1563800791,False,"{'reputation': 1, 'user_id': 11170905, 'user_t...",57146253,NaN,0
6,0,True,5,300,300,0,100808531,1563800791,False,"{'reputation': 3, 'user_id': 11805244, 'user_t...",57116333,NaN,0
7,0,True,5,300,300,0,100808530,1563800789,False,"{'reputation': 417, 'user_id': 7523658, 'user_...",57141227,"{'reputation': 606, 'user_id': 6183113, 'user_...",0
8,0,True,5,300,300,0,100808529,1563800788,False,"{'reputation': 835737, 'user_id': 1144035, 'us...",57143734,NaN,0
9,0,True,5,300,300,0,100808528,1563800786,False,"{'reputation': 36, 'user_id': 11725140, 'user_...",57146614,"{'reputation': 8532, 'user_id': 1136527, 'user...",0
10,0,True,5,300,300,0,100808527,1563800785,False,"{'reputation': 748202, 'user_id': 100297, 'use...",55587268,NaN,0
11,0,True,5,300,300,0,100808526,1563800783,False,"{'reputation': 321, 'user_id': 10989990, 'user...",57143659,"{'reputation': 21, 'user_id': 11291132, 'user_...",0
12,0,True,5,300,300,0,100808525,1563800782,False,"{'reputation': 1635, 'user_id': 10381160, 'use...",57146660,NaN,0
13,0,True,5,300,300,0,100808524,1563800779,False,"{'reputation': 765, 'user_id': 11363596, 'user...",57145962,NaN,0
14,0,True,5,300,300,0,100808523,1563800779,False,"{'reputation': 70616, 'user_id': 1631193, 'use...",57145737,NaN,0
15,0,True,5,300,300,0,100808522,1563800777,False,"{'reputation': 20780, 'user_id': 2815635, 'use...",57146660,NaN,0
16,0,True,5,300,300,0,100808521,1563800775,False,"{'reputation': 1, 'user_id': 11785503, 'user_t...",57146719,NaN,0
17,0,True,5,300,300,0,100808520,1563800775,False,"{'reputation': 4, 'user_id': 11760551, 'user_t...",57146555,NaN,0
18,0,True,5,300,300,0,100808519,1563800769,False,"{'reputation': 15634, 'user_id': 7111561, 'use...",57143990,NaN,0
19,0,True,5,300,300,0,100808518,1563800766,False,"{'reputation': 3, 'user_id': 10494964, 'user_t...",57146552,NaN,0
20,0,True,5,300,300,0,100808517,1563800766,False,"{'reputation': 1051, 'user_id': 3370124, 'user...",57146594,NaN,0
21,0,True,5,300,300,0,100808516,1563800766,False,"{'reputation': 606, 'user_id': 2110865, 'user_...",57146209,"{'reputation': 1523, 'user_id': 8718773, 'user...",0
22,0,True,5,300,300,0,100808515,1563800765,False,"{'reputation': 24860, 'user_id': 448932, 'user...",57146459,NaN,0
23,0,True,5,300,300,0,100808514,1563800763,False,"{'reputation': 6, 'user_id': 3433923, 'user_ty...",57146250,"{'reputation': 12071, 'user_id': 878532, 'user...",0
24,0,True,5,300,300,0,100808513,1563800761,False,"{'reputation': 1, 'user_id': 11604590, 'user_t...",56510078,NaN,0
25,0,True,5,300,300,0,100808512,1563800759,False,"{'reputation': 117, 'user_id': 314282, 'user_t...",57144295,NaN,0
26,0,True,5,300,300,0,100808511,1563800754,False,"{'reputation': 42826, 'user_id': 2988730, 'use...",57146648,NaN,0
27,0,True,5,300,300,0,100808510,1563800754,False,"{'reputation': 7887, 'user_id': 214525, 'user_...",57146560,NaN,0
28,0,True,5,300,300,0,100808509,1563800753,False,"{'reputation': 32789, 'user_id': 1782792, 'use...",57146578,NaN,0
29,0,True,5,300,300,0,100808508,1563800752,False,"{'reputation': 477, 'user_id': 2138953, 'user_...",57146655,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,0,True,5,300,300,0,100808032,1563799934,False,"{'reputation': 306, 'user_id': 3235916, 'user_...",57146233,"{'reputation': 765, 'user_id': 11363596, 'user...",0
471,0,True,5,300,300,0,100808031,1563799933,False,"{'reputation': 19965, 'user_id': 3181392, 'use...",57145558,NaN,0
472,0,True,5,300,300,0,100808030,1563799930,False,"{'reputation': 676933, 'user_id': 19068, 'user...",57146288,"{'reputation': 7432, 'user_id': 3689450, 'user...",0
473,0,True,5,300,300,0,100808029,1563799926,False,"{'reputation': 373, 'user_id': 4376373, 'user_...",57134966,NaN,0
474,0,True,5,300,300,0,100808028,1563799924,False,"{'reputation': 1, 'user_id': 11804757, 'user_t...",57101659,NaN,0
475,0,True,5,300,300,0,100808027,1563799923,False,"{'reputation': 2249, 'user_id': 273125, 'user_...",57146053,NaN,0
476,0,True,5,300,300,0,100808026,1563799923,False,"{'reputation': 10469, 'user_id': 3992939, 'use...",57141777,NaN,0
477,0,True,5,300,300,0,100808025,1563799923,False,"{'reputation': 1, 'user_id': 8774724, 'user_ty...",57137628,NaN,0
478,0,True,5,300,300,0,100808021,1563799917,False,"{'reputation': 15721, 'user_id': 1485219, 'use...",14224813,NaN,0
479,0,True,5,300,300,0,100808020,1563799915,False,"{'reputation': 20, 'user_id': 11759165, 'user_...",57143455,NaN,1
480,0,True,5,300,300,0,100808019,1563799911,False,"{'reputation': 863, 'user_id': 477902, 'user_t...",57145225,"{'reputation': 756, 'user_id': 4453205, 'user_...",0
481,0,True,5,300,300,0,100808017,1563799909,False,"{'reputation': 4113, 'user_id': 6933993, 'user...",57141682,NaN,0
482,0,True,5,300,300,0,100808016,1563799906,False,"{'reputation': 15695, 'user_id': 2202415, 'use...",57146346,NaN,2
483,0,True,5,300,300,0,100808015,1563799903,False,"{'reputation': 175, 'user_id': 7646358, 'user_...",57141415,NaN,0
484,0,True,5,300,300,0,100808014,1563799901,False,"{'reputation': 6, 'user_id': 11629787, 'user_t...",57146055,"{'reputation': 27034, 'user_id': 7328782, 'use...",0
485,0,True,5,300,300,0,100808013,1563799900,False,"{'reputation': 445, 'user_id': 8036445, 'user_...",57146257,"{'reputation': 5125, 'user_id': 933198, 'user_...",0
486,0,True,5,300,300,0,100808012,1563799898,False,"{'reputation': 20707, 'user_id': 5168011, 'use...",57143585,NaN,0
487,0,True,5,300,300,0,100808011,1563799898,False,"{'reputation': 1336, 'user_id': 445877, 'user_...",57146008,"{'reputation': 627, 'user_id': 8101634, 'user_...",0
488,0,True,5,300,300,0,100808010,1563799897,False,"{'reputation': 54, 'user_id': 11611337, 'user_...",57146143,"{'reputation': 675, 'user_id': 4265824, 'user_...",0
489,0,True,5,300,300,0,100808009,1563799896,False,"{'reputation': 759, 'user_id': 3197702, 'user_...",37079434,NaN,0
490,0,True,5,300,300,0,100808008,1563799892,False,"{'reputation': 1084, 'user_id': 1889192, 'user...",57142729,"{'reputation': 339, 'user_id': 10551540, 'user...",0
491,0,True,5,300,300,0,100808006,1563799890,False,"{'reputation': 90, 'user_id': 8373141, 'user_t...",54846839,NaN,0
492,0,True,5,300,300,0,100808005,1563799888,False,"{'reputation': 31083, 'user_id': 9097906, 'use...",57145543,"{'reputation': 299, 'user_id': 5328531, 'user_...",1
493,0,True,5,300,300,0,100808004,1563799887,False,"{'reputation': 68, 'user_id': 10717402, 'user_...",57146162,NaN,0
494,0,True,5,300,300,0,100808003,1563799887,False,"{'reputation': 107, 'user_id': 5244415, 'user_...",57120137,NaN,0
495,0,True,5,300,300,0,100808001,1563799886,False,"{'reputation': 8570, 'user_id': 5025009, 'user...",29680339,NaN,0
496,0,True,5,300,300,0,100808000,1563799886,False,"{'reputation': 592, 'user_id': 4597780, 'user_...",57145340,NaN,0
497,0,True,5,300,300,0,100807999,1563799882,False,"{'reputation': 2722, 'user_id': 1592364, 'user...",57143018,"{'reputation': 173, 'user_id': 10719369, 'user...",0
498,0,True,5,300,300,0,100807998,1563799877,False,"{'reputation': 54, 'user_id': 11611337, 'user_...",57146143,"{'reputation': 321, 'user_id': 9130759, 'user_...",0
499,0,True,5,300,300,0,100807997,1563799874,False,"{'reputation': 8525, 'user_id': 2413201, 'user...",57136056,NaN,0

In [5]:
nested_column = ['items_owner']
flatter = flatten(flat, nested_column)
flatter

,backoff,has_more,page,quota_max,quota_remaining,total,items_comment_id,items_creation_date,items_edited,items_post_id,items_reply_to_user,items_score,items_owner_accept_rate,items_owner_display_name,items_owner_link,items_owner_profile_image,items_owner_reputation,items_owner_user_id,items_owner_user_type
0,0,True,5,300,300,0,100808537,1563800803,False,57146630,NaN,0,NaN,Aris Martin Accola,https://stackoverflow.com/users/11225383/aris-...,https://www.gravatar.com/avatar/11570d1f56e9fd...,1,11225383,registered
1,0,True,5,300,300,0,100808536,1563800803,False,54700076,NaN,0,17,Maneesh Rao,https://stackoverflow.com/users/5694740/manees...,https://lh5.googleusercontent.com/-_cXio_A1-fI...,68,5694740,registered
2,0,True,5,300,300,0,100808535,1563800801,False,57145644,NaN,0,NaN,Axel Richter,https://stackoverflow.com/users/3915431/axel-r...,https://www.gravatar.com/avatar/2ad2fe8d0c0e72...,28468,3915431,registered
3,0,True,5,300,300,0,100808534,1563800800,False,57119783,"{'reputation': 325, 'user_id': 10012519, 'user...",0,NaN,ribs2spare,https://stackoverflow.com/users/5549431/ribs2s...,https://i.stack.imgur.com/uYsPz.jpg?s=128&g=1,138,5549431,registered
4,0,True,5,300,300,0,100808533,1563800791,False,57102174,NaN,0,NaN,Livya Harika chowdary,https://stackoverflow.com/users/11678098/livya...,https://lh4.googleusercontent.com/-q0BSVKvVbaw...,1,11678098,registered
5,0,True,5,300,300,0,100808532,1563800791,False,57146253,NaN,0,NaN,Ali Aydin,https://stackoverflow.com/users/11170905/ali-a...,https://www.gravatar.com/avatar/7a73ff9f493512...,1,11170905,registered
6,0,True,5,300,300,0,100808531,1563800791,False,57116333,NaN,0,NaN,omega957,https://stackoverflow.com/users/11805244/omega957,https://www.gravatar.com/avatar/542a6ab31c749e...,3,11805244,registered
7,0,True,5,300,300,0,100808530,1563800789,False,57141227,"{'reputation': 606, 'user_id': 6183113, 'user_...",0,46,BGTabulation BGTabulate,https://stackoverflow.com/users/7523658/bgtabu...,https://www.gravatar.com/avatar/98e3589425f8f1...,417,7523658,registered
8,0,True,5,300,300,0,100808529,1563800788,False,57143734,NaN,0,NaN,Gordon Linoff,https://stackoverflow.com/users/1144035/gordon...,https://www.gravatar.com/avatar/e514b017977ebf...,835737,1144035,registered
9,0,True,5,300,300,0,100808528,1563800786,False,57146614,"{'reputation': 8532, 'user_id': 1136527, 'user...",0,NaN,mongoose00318,https://stackoverflow.com/users/11725140/mongo...,https://www.gravatar.com/avatar/7515ca6774d9b0...,36,11725140,registered
10,0,True,5,300,300,0,100808527,1563800785,False,55587268,NaN,0,NaN,Martijn Pieters,https://stackoverflow.com/users/100297/martijn...,https://www.gravatar.com/avatar/24780fb6df85a9...,748202,100297,moderator
11,0,True,5,300,300,0,100808526,1563800783,False,57143659,"{'reputation': 21, 'user_id': 11291132, 'user_...",0,NaN,Priyankagb,https://stackoverflow.com/users/10989990/priya...,https://www.gravatar.com/avatar/a40509232269e4...,321,10989990,registered
12,0,True,5,300,300,0,100808525,1563800782,False,57146660,NaN,0,NaN,CodeBoyCode,https://stackoverflow.com/users/10381160/codeb...,https://i.stack.imgur.com/ZCtEC.jpg?s=128&g=1,1635,10381160,registered
13,0,True,5,300,300,0,100808524,1563800779,False,57145962,NaN,0,NaN,Vishal,https://stackoverflow.com/users/11363596/vishal,https://www.gravatar.com/avatar/5f37f85a4f09c7...,765,11363596,registered
14,0,True,5,300,300,0,100808523,1563800779,False,57145737,NaN,0,71,Gabe Sechan,https://stackoverflow.com/users/1631193/gabe-s...,https://www.gravatar.com/avatar/87710a44c44562...,70616,1631193,registered
15,0,True,5,300,300,0,100808522,1563800777,False,57146660,NaN,0,89,Niklesh Raut,https://stackoverflow.com/users/2815635/nikles...,https://i.stack.imgur.com/mDBvL.png?s=128&g=1,20780,2815635,registered
16,0,True,5,300,300,0,100808521,1563800775,False,57146719,NaN,0,NaN,Ak Ak,https://stackoverflow.com/users/11785503/ak-ak,https://lh6.googleusercontent.com/-vHGPddOR9pI...,1,11785503,registered
17,0,True,5,300,300,0,100808520,1563800775,False,57146555,NaN,0,NaN,mikeneumannd,https://stackoverflow.com/users/11760551/miken...,https://www.gravatar.com/avatar/089f4a197f6717...,4,11760551,registered
18,0,True,5,300,300,0,100808519,1563800769,False,57143990,NaN,0,54,derHugo,https://stackoverflow.com/users/7111561/derhugo,https://i.stack.imgur.com/SNnq7.png?s=128&g=1,15634,7111561,registered
19,0,True,5,300,300,0,100808518,1563800766,False,57146552,NaN,0,NaN,seilf,https://stackoverflow.com/users/10494964/seilf,https://i.stack.imgur.com/4AnNP.jpg?s=128&g=1,3,10494964,registered
20,0,True,5,300,300,0,100808517,1563800766,False,57146594,NaN,0,NaN,Richard Critten,https://stackoverflow.com/users/3370124/richar...,https://www.gravatar.com/avatar/f73352b4adb282...,1051,3370124,registered
21,0,True,5,300,300,0,100808516,1563800766,False,57146209,"{'reputation': 1523, 'user_id': 8718773, 'user...",0,50,thanos.a,https://stackoverflow.com/users/2110865/thanos-a,https://www.gravatar.com/avatar/cf325fa3380242...,606,2110865,registered
22,0,True,5,300,300,0,100808515,1563800765,False,57146459,NaN,0,NaN,500 - Internal Server Error,https://stackoverflow.com/users/448932/500-int...,https://i.stack.imgur.com/QgLLl.png?s=128&g=1,24860,448932,registered
23,0,True,5,300,300,0,100808514,1563800763,False,57146250,"{'reputation': 12071, 'user_id': 878532, 'user...",0,NaN,Youri,https://stackoverflow.com/users/3433923/youri,https://www.gravatar.com/avatar/7620fe91d66995...,6,3433923,registered
24,0,True,5,300,300,0,100808513,1563800761,False,56510078,NaN,0,NaN,SahondraGaby,https://stackoverflow.com/users/11604590/sahon...,https://www.gravatar.com/avatar/ac251d6961761a...,1,11604590,registered
25,0,True,5,300,300,0,100808512,1563800759,False,57144295,NaN,0,50,Amit Kumar Jain,https://stackoverflow.com/users/314282/amit-ku...,https://www.gravatar.com/avatar/e497c253072f0e...,117,314282,registered
26,0,True,5,300,300,0,100808511,1563800754,False,57146648,NaN,0,96,Mad Physicist,https://stackoverflow.com/users/2988730/mad-ph...,https://i.stack.imgur.com/ZOX7t.jpg?s=128&g=1,42826,2988730,registered
27,0,True,5,300,300,0,100808510,1563800754,False,57146560,NaN,0,100,f1sh,https://stackoverflow.com/users/214525/f1sh,https://www.gravatar.com/avatar/7684a686e23347...,7887,214525,registered
28,0,True,5,300,300,0,100808509,1563800753,False,57146578,NaN,0,100,jdehesa,https://stackoverflow.com/users/1782792/jdehesa,https://www.gravatar.com/avatar/7e8dde1ee800b9...,32789,1782792,registered
29,0,True,5,300,300,0,100808508,1563800752,False,57146655,NaN,0,83,PAX,https://stackoverflow.com/users/2138953/pax,https://www.gravatar.com/avatar/8cd04b814ccbc2...,477,2138953,registered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,0,True,5,300,300,0,100808032,1563799934,False,57146233,"{'reputation': 765, 'user_id': 11363596, 'user...",0,80,user3235916,https://stackoverflow.com/users/3235916/user32...,https://www.gravatar.com/avatar/127b9983cea62f...,306,3235916,registered
471,0,True,5,300,300,0,100808031,1563799933,False,57145558,NaN,0,NaN,cfrick,https://stackoverflow.com/users/3181392/cfrick,https://i.stack.imgur.com/SIgPs.png?s=128&g=1,19965,3181392,registered
472,0,True,5,300,300,0,100808030,1563799930,False,57146288,"{'reputation': 7432, 'user_id': 3689450, 'user...",0,NaN,Quentin,https://stackoverflow.com/users/19068/quentin,https://www.gravatar.com/avatar/1d2d3229ed1961...,676933,19068,registered
473,0,True,5,300,300,0,100808029,1563799926,False,57134966,NaN,0,89,Patrick Kelly,https://stackoverflow.com/users/4376373/patric...,https://graph.facebook.com/100006052897811/pic...,373,4376373,registered
474,0,True,5,300,300,0,100808028,1563799924,False,57101659,NaN,0,NaN,PBocca,https://stackoverflow.com/users/11804757/pbocca,https://www.gravatar.com/avatar/b0ecf67d53761a...,1,11804757,registered
475,0,True,5,300,300,0,100808027,1563799923,False,57146053,NaN,0,100,Frank Martin,https://stackoverflow.com/users/273125/frank-m...,https://i.stack.imgur.com/pdRYz.jpg?s=128&g=1,2249,273125,registered
476,0,True,5,300,300,0,100808026,1563799923,False,57141777,NaN,0,73,c0der,https://stackoverflow.com/users/3992939/c0der,https://i.stack.imgur.com/JNHZt.jpg?s=128&g=1,10469,3992939,registered
477,0,True,5,300,300,0,100808025,1563799923,False,57137628,NaN,0,NaN,Khurram Khalil,https://stackoverflow.com/users/8774724/khurra...,https://i.stack.imgur.com/uxQQr.jpg?s=128&g=1,1,8774724,registered
478,0,True,5,300,300,0,100808021,1563799917,False,14224813,NaN,0,NaN,oleq,https://stackoverflow.com/users/1485219/oleq,https://www.gravatar.com/avatar/c970342817d958...,15721,1485219,registered
479,0,True,5,300,300,0,100808020,1563799915,False,57143455,NaN,1,NaN,Hamza Mirchi,https://stackoverflow.com/users/11759165/hamza...,https://lh4.googleusercontent.com/-TajPrYFW_g4...,20,11759165,registered
480,0,True,5,300,300,0,100808019,1563799911,False,57145225,"{'reputation': 756, 'user_id': 4453205, 'user_...",0,93,flakerimi,https://stackoverflow.com/users/477902/flakerimi,https://www.gravatar.com/avatar/1e3c0278f39a98...,863,477902,registered
481,0,True,5,300,300,0,100808017,1563799909,False,57141682,NaN,0,97,thebluephantom,https://stackoverflow.com/users/6933993/theblu...,https://i.stack.imgur.com/8rS8O.jpg?s=128&g=1,4113,6933993,registered
482,0,True,5,300,300,0,100808016,1563799906,False,57146346,NaN,2,NaN,Maciej Kowalski,https://stackoverflow.com/users/2202415/maciej...,https://i.stack.imgur.com/SESvu.jpg?s=128&g=1,15695,2202415,registered
483,0,True,5,300,300,0,100808015,1563799903,False,57141415,NaN,0,62,MTZ,https://stackoverflow.com/users/7646358/mtz,https://graph.facebook.com/1487116991340979/pi...,175,7646358,registered
484,0,True,5,300,300,0,100808014,1563799901,False,57146055,"{'reputation': 27034, 'user_id': 7328782, 'use...",0,NaN,krank s,https://stackoverflow.com/users/11629787/krank-s,https://lh6.googleusercontent.com/-cVmDAfHybAg...,6,11629787,registered
485,0,True,5,300,300,0,100808013,1563799900,False,57146257,"{'reputation': 5125, 'user_id': 933198, 'user_...",0,NaN,Velu Dhanesh,https://stackoverflow.com/users/8036445/velu-d...,https://lh3.googleusercontent.com/-TPQUwUK2q8w...,445,8036445,registered
486,0,True,5,300,300,0,100808012,1563799898,False,57143585,NaN,0,100,Guy,https://stackoverflow.com/users/5168011/guy,https://www.gravatar.com/avatar/eb70c32e1e533e...,20707,5168011,registered
487,0,True,5,300,300,0,100808011,1563799898,False,57146008,"{'reputation': 627, 'user_id': 8101634, 'user_...",0,NaN,Alex Hart,https://stackoverflow.com/users/445877/alex-hart,https://www.gravatar.com/avatar/93efa37f5b47aa...,1336,445877,registered
488,0,True,5,300,300,0,100808010,1563799897,False,57146143,"{'reputation': 675, 'user_id': 4265824, 'user_...",0,NaN,Hirose,https://stackoverflow.com/users/11611337/hirose,https://i.stack.imgur.com/2wFE5.jpg?s=128&g=1,54,11611337,registered
489,0,True,5,300,300,0,100808009,1563799896,False,37079434,NaN,0,75,Nicolas Leucci,https://stackoverflow.com/users/3197702/nicola...,https://www.gravatar.com/avatar/25c2b96a4ca727...,759,3197702,registered
490,0,True,5,300,300,0,100808008,1563799892,False,57142729,"{'reputation': 339, 'user_id': 10551540, 'user...",0,67,inherithandle,https://stackoverflow.com/users/1889192/inheri...,https://www.gravatar.com/avatar/9a1946c8e16bd4...,1084,1889192,registered
491,0,True,5,300,300,0,100808006,1563799890,False,54846839,NaN,0,NaN,CarpeDiemKopi,https://stackoverflow.com/users/8373141/carped...,https://www.gravatar.com/avatar/2d258d68788c13...,90,8373141,registered
492,0,True,5,300,300,0,100808005,1563799888,False,57145543,"{'reputation': 299, 'user_id': 5328531, 'user_...",1,NaN,Littlefoot,https://stackoverflow.com/users/9097906/little...,https://i.stack.imgur.com/RmIqt.jpg?s=128&g=1,31083,9097906,registered
493,0,True,5,300,300,0,100808004,1563799887,False,57146162,NaN,0,NaN,usman saleem,https://stackoverflow.com/users/10717402/usman...,https://lh4.googleusercontent.com/-Fti4vlDwciI...,68,10717402,registered
494,0,True,5,300,300,0,100808003,1563799887,False,57120137,NaN,0,100,Estevao Santiago,https://stackoverflow.com/users/5244415/esteva...,https://i.stack.imgur.com/dXXKV.jpg?s=128&g=1,107,5244415,registered
495,0,True,5,300,300,0,100808001,1563799886,False,29680339,NaN,0,NaN,serafeim,https://stackoverflow.com/users/5025009/serafeim,https://i.stack.imgur.com/P7Ks4.png?s=128&g=1,8570,5025009,registered
496,0,True,5,300,300,0,100808000,1563799886,False,57145340,NaN,0,100,Jonhy Beebop,https://stackoverflow.com/users/4597780/jonhy-...,https://www.gravatar.com/avatar/564d17f80e7482...,592,4597780,registered
497,0,True,5,300,300,0,100807999,1563799882,False,57143018,"{'reputation': 173, 'user_id': 10719369, 'user...",0,100,Ankur Sinha,https://stackoverflow.com/users/1592364/ankur-...,https://i.stack.imgur.com/m2TxY.jpg?s=128&g=1,2722,1592364,registered
498,0,True,5,300,300,0,100807998,1563799877,False,57146143,"{'reputation': 321, 'user_id': 9130759, 'user_...",0,NaN,Hirose,https://stackoverflow.com/users/11611337/hirose,https://i.stack.imgur.com/2wFE5.jpg?s=128&g=1,54,11611337,registered
499,0,True,5,300,300,0,100807997,1563799874,False,57136056,NaN,0,88,Armali,https://stackoverflow.com/users/2413201/armali,https://i.stack.imgur.com/rxfuw.jpg?s=128&g=1,8525,2413201,registered

In [6]:
flattest = flatten(flatter, ["items_reply_to_user"])
flattest

,backoff,has_more,page,quota_max,quota_remaining,total,items_comment_id,items_creation_date,items_edited,items_post_id,...,items_owner_reputation,items_owner_user_id,items_owner_user_type,items_reply_to_user_accept_rate,items_reply_to_user_display_name,items_reply_to_user_link,items_reply_to_user_profile_image,items_reply_to_user_reputation,items_reply_to_user_user_id,items_reply_to_user_user_type
0,0,True,5,300,300,0,100808537,1563800803,False,57146630,...,1,11225383,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,True,5,300,300,0,100808536,1563800803,False,54700076,...,68,5694740,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,True,5,300,300,0,100808535,1563800801,False,57145644,...,28468,3915431,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,True,5,300,300,0,100808534,1563800800,False,57119783,...,138,5549431,registered,NaN,alexherm,https://stackoverflow.com/users/10012519/alexherm,https://lh3.googleusercontent.com/-UXVWJ2vzUBg...,325,10012519,registered
4,0,True,5,300,300,0,100808533,1563800791,False,57102174,...,1,11678098,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0,True,5,300,300,0,100808532,1563800791,False,57146253,...,1,11170905,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0,True,5,300,300,0,100808531,1563800791,False,57116333,...,3,11805244,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0,True,5,300,300,0,100808530,1563800789,False,57141227,...,417,7523658,registered,NaN,ORBIT,https://stackoverflow.com/users/6183113/orbit,https://i.stack.imgur.com/AL7Dr.jpg?s=128&g=1,606,6183113,registered
8,0,True,5,300,300,0,100808529,1563800788,False,57143734,...,835737,1144035,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0,True,5,300,300,0,100808528,1563800786,False,57146614,...,36,11725140,registered,65,Alex McMillan,https://stackoverflow.com/users/1136527/alex-m...,https://i.stack.imgur.com/LpVhn.jpg?s=128&g=1,8532,1136527,registered
10,0,True,5,300,300,0,100808527,1563800785,False,55587268,...,748202,100297,moderator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0,True,5,300,300,0,100808526,1563800783,False,57143659,...,321,10989990,registered,NaN,Rakesh,https://stackoverflow.com/users/11291132/rakesh,https://lh6.googleusercontent.com/-Xpdro73MQxQ...,21,11291132,registered
12,0,True,5,300,300,0,100808525,1563800782,False,57146660,...,1635,10381160,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0,True,5,300,300,0,100808524,1563800779,False,57145962,...,765,11363596,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0,True,5,300,300,0,100808523,1563800779,False,57145737,...,70616,1631193,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0,True,5,300,300,0,100808522,1563800777,False,57146660,...,20780,2815635,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0,True,5,300,300,0,100808521,1563800775,False,57146719,...,1,11785503,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0,True,5,300,300,0,100808520,1563800775,False,57146555,...,4,11760551,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0,True,5,300,300,0,100808519,1563800769,False,57143990,...,15634,7111561,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0,True,5,300,300,0,100808518,1563800766,False,57146552,...,3,10494964,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0,True,5,300,300,0,100808517,1563800766,False,57146594,...,1051,3370124,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0,True,5,300,300,0,100808516,1563800766,False,57146209,...,606,2110865,registered,NaN,Giacomo Alzetta,https://stackoverflow.com/users/8718773/giacom...,https://www.gravatar.com/avatar/34213fbac0a5b0...,1523,8718773,registered
22,0,True,5,300,300,0,100808515,1563800765,False,57146459,...,24860,448932,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0,True,5,300,300,0,100808514,1563800763,False,57146250,...,6,3433923,registered,66,Klaus,https://stackoverflow.com/users/878532/klaus,https://www.gravatar.com/avatar/5fbebb625a2892...,12071,878532,registered
24,0,True,5,300,300,0,100808513,1563800761,False,56510078,...,1,11604590,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0,True,5,300,300,0,100808512,1563800759,False,57144295,...,117,314282,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0,True,5,300,300,0,100808511,1563800754,False,57146648,...,42826,2988730,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0,True,5,300,300,0,100808510,1563800754,False,57146560,...,7887,214525,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0,True,5,300,300,0,100808509,1563800753,False,57146578,...,32789,1782792,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0,True,5,300,300,0,100808508,1563800752,False,57146655,...,477,2138953,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,0,True,5,300,300,0,100808032,1563799934,False,57146233,...,306,3235916,registered,NaN,Vishal,https://stackoverflow.com/users/11363596/vishal,https://www.gravatar.com/avatar/5f37f85a4f09c7...,765,11363596,registered
471,0,True,5,300,300,0,100808031,1563799933,False,57145558,...,19965,3181392,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,0,True,5,300,300,0,100808030,1563799930,False,57146288,...,676933,19068,registered,NaN,VLAZ,https://stackoverflow.com/users/3689450/vlaz,https://i.stack.imgur.com/NfVJ4.png?s=128&g=1,7432,3689450,registered
473,0,True,5,300,300,0,100808029,1563799926,False,57134966,...,373,4376373,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,0,True,5,300,300,0,100808028,1563799924,False,57101659,...,1,11804757,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,0,True,5,300,300,0,100808027,1563799923,False,57146053,...,2249,273125,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,0,True,5,300,300,0,100808026,1563799923,False,57141777,...,10469,3992939,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,0,True,5,300,300,0,100808025,1563799923,False,57137628,...,1,8774724,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,0,True,5,300,300,0,100808021,1563799917,False,14224813,...,15721,1485219,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,0,True,5,300,300,0,100808020,1563799915,False,57143455,...,20,11759165,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,0,True,5,300,300,0,100808019,1563799911,False,57145225,...,863,477902,registered,NaN,10101010,https://stackoverflow.com/users/4453205/10101010,https://i.stack.imgur.com/zMvhx.jpg?s=128&g=1,756,4453205,registered
481,0,True,5,300,300,0,100808017,1563799909,False,57141682,...,4113,6933993,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,0,True,5,300,300,0,100808016,1563799906,False,57146346,...,15695,2202415,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,0,True,5,300,300,0,100808015,1563799903,False,57141415,...,175,7646358,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,0,True,5,300,300,0,100808014,1563799901,False,57146055,...,6,11629787,registered,86,Cris Luengo,https://stackoverflow.com/users/7328782/cris-l...,https://i.stack.imgur.com/treJu.png?s=128&g=1,27034,7328782,registered
485,0,True,5,300,300,0,100808013,1563799900,False,57146257,...,445,8036445,registered,88,Lee Taylor,https://stackoverflow.com/users/933198/lee-taylor,https://www.gravatar.com/avatar/25a22103fd3210...,5125,933198,registered
486,0,True,5,300,300,0,100808012,1563799898,False,57143585,...,20707,5168011,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,0,True,5,300,300,0,100808011,1563799898,False,57146008,...,1336,445877,registered,NaN,primo,https://stackoverflow.com/users/8101634/primo,https://www.gravatar.com/avatar/2071bbc2522f51...,627,8101634,registered
488,0,True,5,300,300,0,100808010,1563799897,False,57146143,...,54,11611337,registered,45,Ganesh Gudghe,https://stackoverflow.com/users/4265824/ganesh...,https://i.stack.imgur.com/zwjaH.jpg?s=128&g=1,675,4265824,registered
489,0,True,5,300,300,0,100808009,1563799896,False,37079434,...,759,3197702,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,0,True,5,300,300,0,100808008,1563799892,False,57142729,...,1084,1889192,registered,NaN,Robert garcia,https://stackoverflow.com/users/10551540/rober...,https://www.gravatar.com/avatar/c6eaa79ed71fb5...,339,10551540,registered
491,0,True,5,300,300,0,100808006,1563799890,False,54846839,...,90,8373141,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,0,True,5,300,300,0,100808005,1563799888,False,57145543,...,31083,9097906,registered,75,Md Wasi,https://stackoverflow.com/users/5328531/md-wasi,https://i.stack.imgur.com/SrNr9.jpg?s=128&g=1,299,5328531,registered
493,0,True,5,300,300,0,100808004,1563799887,False,57146162,...,68,10717402,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,0,True,5,300,300,0,100808003,1563799887,False,57120137,...,107,5244415,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,0,True,5,300,300,0,100808001,1563799886,False,29680339,...,8570,5025009,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,0,True,5,300,300,0,100808000,1563799886,False,57145340,...,592,4597780,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,0,True,5,300,300,0,100807999,1563799882,False,57143018,...,2722,1592364,registered,NaN,Mari,https://stackoverflow.com/users/10719369/mari,https://lh3.googleusercontent.com/-XdUIqdMkCWA...,173,10719369,registered
498,0,True,5,300,300,0,100807998,1563799877,False,57146143,...,54,11611337,registered,NaN,Mini Chip,https://stackoverflow.com/users/9130759/mini-chip,https://i.stack.imgur.com/7Jm9w.png?s=128&g=1,321,9130759,registered
499,0,True,5,300,300,0,100807997,1563799874,False,57136056,...,8525,2413201,registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
questions_answers = flattest[["items_comment_id", "items_reply_to_user_user_id"]]
questions_answers
# The comment and reply IDs below

    items_comment_id items_reply_to_user_user_id
0          100808537                         NaN
1          100808536                         NaN
2          100808535                         NaN
3          100808534                    10012519
4          100808533                         NaN
5          100808532                         NaN
6          100808531                         NaN
7          100808530                     6183113
8          100808529                         NaN
9          100808528                     1136527
10         100808527                         NaN
11         100808526                    11291132
12         100808525                         NaN
13         100808524                         NaN
14         100808523                         NaN
15         100808522                         NaN
16         100808521                         NaN
17         100808520                         NaN
18         100808519                         NaN
19         100808518                         NaN
20         100808517                         NaN
21         100808516                     8718773
22         100808515                         NaN
23         100808514                      878532
24         100808513                         NaN
25         100808512                         NaN
26         100808511                         NaN
27         100808510                         NaN
28         100808509                         NaN
29         100808508                         NaN
..               ...                         ...
470        100808032                    11363596
471        100808031                         NaN
472        100808030                     3689450
473        100808029                         NaN
474        100808028                         NaN
475        100808027                         NaN
476        100808026                         NaN
477        100808025                         NaN
478        100808021                         NaN
479        100808020                         NaN
480        100808019                     4453205
481        100808017                         NaN
482        100808016                         NaN
483        100808015                         NaN
484        100808014                     7328782
485        100808013                      933198
486        100808012                         NaN
487        100808011                     8101634
488        100808010                     4265824
489        100808009                         NaN
490        100808008                    10551540
491        100808006                         NaN
492        100808005                     5328531
493        100808004                         NaN
494        100808003                         NaN
495        100808001                         NaN
496        100808000                         NaN
497        100807999                    10719369
498        100807998                     9130759
499        100807997                         NaN

[500 rows x 2 columns]

#### Question 2: Find the most voted question today with at least a score of 5 and tagged with 'python'.

In [8]:
# your code here
questions_today = SITE.fetch("questions", fromdate=1457136000, todate=1457222400)
questions_data = pd.DataFrame(questions_today)
questions_data
# Does not work when I add 'fromdate=datetime(2019,7,10), todate=datetime(2019,7,11) so i copied the dates in the stackoverflow readme

,backoff,has_more,page,quota_max,quota_remaining,total,items
0,0,True,5,300,300,0,"{'tags': ['ios', 'swift', 'avfoundation'], 'ow..."
1,0,True,5,300,300,0,"{'tags': ['rust', 'rust-cargo'], 'owner': {'re..."
2,0,True,5,300,300,0,"{'tags': ['bash', 'shell', 'unix', 'pipelining..."
3,0,True,5,300,300,0,"{'tags': ['android', 'tabs', 'scrollable'], 'o..."
4,0,True,5,300,300,0,"{'tags': ['python', 'binary-search-tree', 'dou..."
5,0,True,5,300,300,0,"{'tags': ['python', 'python-2.7', 'flask', 'sq..."
6,0,True,5,300,300,0,"{'tags': ['node.js', 'alexa-skills-kit'], 'own..."
7,0,True,5,300,300,0,"{'tags': ['android', 'android-layout'], 'owner..."
8,0,True,5,300,300,0,"{'tags': ['wordpress', 'redirect'], 'owner': {..."
9,0,True,5,300,300,0,"{'tags': ['npm', 'webpack'], 'owner': {'reputa..."
10,0,True,5,300,300,0,"{'tags': ['python', 'templates', 'flask', 'jin..."
11,0,True,5,300,300,0,"{'tags': ['node.js', 'mongodb', 'mean-stack'],..."
12,0,True,5,300,300,0,"{'tags': ['java', 'android', 'facebook', 'null..."
13,0,True,5,300,300,0,"{'tags': ['javascript', 'gulp', 'browserify', ..."
14,0,True,5,300,300,0,"{'tags': ['python', 'image', 'search-engine'],..."
15,0,True,5,300,300,0,"{'tags': ['php', 'ubuntu', 'composer-php', 'ma..."
16,0,True,5,300,300,0,"{'tags': ['javascript', 'ajax', 'internet-expl..."
17,0,True,5,300,300,0,"{'tags': ['css'], 'owner': {'user_type': 'does..."
18,0,True,5,300,300,0,"{'tags': ['javascript', 'documentation', 'jsdo..."
19,0,True,5,300,300,0,"{'tags': ['sql'], 'owner': {'reputation': 13, ..."
20,0,True,5,300,300,0,"{'tags': ['android', 'api', 'detection', 'face..."
21,0,True,5,300,300,0,"{'tags': ['html', 'css'], 'owner': {'reputatio..."
22,0,True,5,300,300,0,"{'tags': ['javascript', 'angular'], 'owner': {..."
23,0,True,5,300,300,0,"{'tags': ['php', 'css', 'wordpress', 'plugins'..."
24,0,True,5,300,300,0,"{'tags': ['inno-setup', 'pascalscript'], 'owne..."
25,0,True,5,300,300,0,"{'tags': ['c#', 'xaml', 'windows-10', 'win-uni..."
26,0,True,5,300,300,0,"{'tags': ['smartcard', 'apdu'], 'owner': {'rep..."
27,0,True,5,300,300,0,"{'tags': ['azure', 'azure-sql-database', 'azur..."
28,0,True,5,300,300,0,"{'tags': ['regex'], 'owner': {'reputation': 56..."
29,0,True,5,300,300,0,"{'tags': ['python', 'selenium', 'web-scraping'..."
...,...,...,...,...,...,...,...
470,0,True,5,300,300,0,"{'tags': ['elasticsearch', 'lucene'], 'owner':..."
471,0,True,5,300,300,0,"{'tags': ['c++', 'qt', 'cmake', 'clion'], 'own..."
472,0,True,5,300,300,0,"{'tags': ['javascript', 'firefox', 'webrtc'], ..."
473,0,True,5,300,300,0,"{'tags': ['ios', 'swift'], 'owner': {'reputati..."
474,0,True,5,300,300,0,"{'tags': ['swift', 'multidimensional-array'], ..."
475,0,True,5,300,300,0,"{'tags': ['javascript', 'markdown', 'showdown'..."
476,0,True,5,300,300,0,"{'tags': ['android', 'arrays', 'json', 'androi..."
477,0,True,5,300,300,0,"{'tags': ['webgl', 'openlayers-3'], 'owner': {..."
478,0,True,5,300,300,0,"{'tags': ['apache-kafka'], 'owner': {'reputati..."
479,0,True,5,300,300,0,"{'tags': ['android', 'android-context'], 'owne..."
480,0,True,5,300,300,0,"{'tags': ['c#', '.net', 'asp.net-mvc-4', 'depe..."
481,0,True,5,300,300,0,"{'tags': ['c#', 'asp.net', 'asp.net-mvc', 'ent..."
482,0,True,5,300,300,0,"{'tags': ['c++', 'qt', 'c++11'], 'owner': {'re..."
483,0,True,5,300,300,0,"{'tags': ['scala', 'apache-spark', 'apache-spa..."
484,0,True,5,300,300,0,"{'tags': ['ruby', 'savon', 'zuora'], 'owner': ..."
485,0,True,5,300,300,0,"{'tags': ['parsing', 'intellij-idea', 'bnf', '..."
486,0,True,5,300,300,0,"{'tags': ['php', 'curl', 'laravel-5'], 'owner'..."
487,0,True,5,300,300,0,"{'tags': ['rest', 'reactjs', 'redux', 'flux', ..."
488,0,True,5,300,300,0,"{'tags': ['php', 'api', 'rest', 'yii2'], 'owne..."
489,0,True,5,300,300,0,"{'tags': ['git', 'git-merge', 'git-rebase'], '..."
490,0,True,5,300,300,0,"{'tags': ['rest', 'security', 'laravel'], 'own..."
491,0,True,5,300,300,0,"{'tags': ['java', 'sorting', 'hadoop', 'mapred..."
492,0,True,5,300,300,0,"{'tags': ['c', 'berkeley-db', 'ssd'], 'owner':..."
493,0,True,5,300,300,0,"{'tags': ['c#', 'ef-code-first', 'asp.net-core..."
494,0,True,5,300,300,0,"{'tags': ['javascript', 'dojo', 'dgrid'], 'own..."
495,0,True,5,300,300,0,"{'tags': ['delphi', 'math', 'numbers', 'firemo..."
496,0,True,5,300,300,0,"{'tags': ['javafx', 'jxbrowser'], 'owner': {'r..."
497,0,True,5,300,300,0,"{'tags': ['java', 'datainputstream'], 'owner':..."
498,0,True,5,300,300,0,"{'tags': ['automation', 'web'], 'owner': {'rep..."
499,0,True,5,300,300,0,"{'tags': ['android', 'maven', 'gradle', 'bintr..."

In [9]:
expanded = flatten(questions_data, ['items'])
expanded

,backoff,has_more,page,quota_max,quota_remaining,total,items_accepted_answer_id,items_answer_count,items_closed_date,items_closed_reason,...,items_last_edit_date,items_link,items_migrated_from,items_owner,items_protected_date,items_question_id,items_score,items_tags,items_title,items_view_count
0,0,True,5,300,300,0,NaN,4,NaN,NaN,...,1515590369,https://stackoverflow.com/questions/35810086/s...,NaN,"{'reputation': 1172, 'user_id': 3333933, 'user...",NaN,35810086,0,"[ios, swift, avfoundation]",Swift IOS Record Video and Audio with AVFounda...,5877
1,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1457220505,https://stackoverflow.com/questions/35821185/h...,NaN,"{'reputation': 352, 'user_id': 5784051, 'user_...",NaN,35821185,6,"[rust, rust-cargo]",How to download the documentation of a crate w...,729
2,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1563703705,https://stackoverflow.com/questions/35820825/w...,NaN,"{'reputation': 106, 'user_id': 735051, 'user_t...",NaN,35820825,13,"[bash, shell, unix, pipelining]",What is the cleanest way to create a non-linea...,338
3,0,True,5,300,300,0,35815668,4,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35815615/h...,NaN,"{'reputation': 88, 'user_id': 5964516, 'user_t...",NaN,35815615,12,"[android, tabs, scrollable]",How to make scrollable tab in Android?,26457
4,0,True,5,300,300,0,NaN,2,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35820604/p...,NaN,"{'reputation': 17, 'user_id': 5192075, 'user_t...",NaN,35820604,1,"[python, binary-search-tree, doubly-linked-list]",python convert sorted Double linked list to BST,441
5,0,True,5,300,300,0,35823039,2,NaN,NaN,...,1536995747,https://stackoverflow.com/questions/35814211/h...,NaN,"{'reputation': 884, 'user_id': 3664629, 'user_...",NaN,35814211,4,"[python, python-2.7, flask, sqlalchemy, flask-...",How to add a custom function/method in sqlalch...,6070
6,0,True,5,300,300,0,35822875,2,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35810418/a...,NaN,"{'reputation': 12059, 'user_id': 3131147, 'use...",NaN,35810418,4,"[node.js, alexa-skills-kit]",Add AMAZON.DURATION to current time,616
7,0,True,5,300,300,0,35814039,1,1560534151,too broad,...,1457182071,https://stackoverflow.com/questions/35813812/h...,NaN,"{'reputation': 55, 'user_id': 3314508, 'user_t...",NaN,35813812,2,"[android, android-layout]",How to do Onboarding in Android,4732
8,0,True,5,300,300,0,NaN,2,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35820404/r...,NaN,"{'reputation': 68, 'user_id': 4438388, 'user_t...",NaN,35820404,0,"[wordpress, redirect]",Redirect wordpress user to another page based ...,1072
9,0,True,5,300,300,0,35817969,20,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35810172/w...,NaN,"{'reputation': 781, 'user_id': 5984184, 'user_...",NaN,35810172,100,"[npm, webpack]",webpack is not recognized as a internal or ext...,122352
10,0,True,5,300,300,0,36160856,2,NaN,NaN,...,1495542894,https://stackoverflow.com/questions/35811448/p...,NaN,"{'reputation': 552, 'user_id': 4162778, 'user_...",NaN,35811448,8,"[python, templates, flask, jinja2, pyinstaller]",Pyinstaller Jinja2 TemplateNotFound,2865
11,0,True,5,300,300,0,35813628,8,NaN,NaN,...,1557397447,https://stackoverflow.com/questions/35813584/m...,NaN,"{'reputation': 327, 'user_id': 5182710, 'user_...",NaN,35813584,34,"[node.js, mongodb, mean-stack]","MongoDB - Error: invalid schema, expected mongodb",34719
12,0,True,5,300,300,0,35818073,1,NaN,NaN,...,1561826101,https://stackoverflow.com/questions/35817950/n...,NaN,"{'reputation': 40, 'user_id': 3592588, 'user_t...",NaN,35817950,1,"[java, android, facebook, nullpointerexception]",Null Pointer exception handling Facebook login...,1053
13,0,True,5,300,300,0,NaN,3,NaN,NaN,...,1457211894,https://stackoverflow.com/questions/35813804/h...,NaN,"{'reputation': 490, 'user_id': 4831427, 'user_...",NaN,35813804,4,"[javascript, gulp, browserify, bundling-and-mi...",How to set up gulp to bundle several files int...,5505
14,0,True,5,300,300,0,35810041,10,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35809554/h...,NaN,"{'reputation': 323, 'user_id': 1002122, 'user_...",NaN,35809554,12,"[python, image, search-engine]",How to download google image search results in...,21672
15,0,True,5,300,300,0,35827555,12,NaN,NaN,...,1457271739,https://stackoverflow.com/questions/35815376/t...,NaN,"{'reputation': 658, 'user_id': 4811466, 'user_...",NaN,35815376,22,"[php, ubuntu, composer-php, magento2]","To enable extensions, verify that they are ena...",73675
16,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1561068096,https://stackoverflow.com/questions/35808557/j...,NaN,"{'reputation': 66, 'user_id': 4690164, 'user_t...",NaN,35808557,13,"[javascript, ajax, internet-explorer, cross-br...",javascript Ajax SCRIPT1003: Expected &#39;:&#3...,17862
17,0,True,5,300,300,0,35821416,4,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35821279/p...,NaN,"{'user_type': 'does_not_exist', 'display_name'...",NaN,35821279,2,[css],Positioning an image inside a text input box,6642
18,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35816620/j...,NaN,"{'reputation': 36512, 'user_id': 379008, 'user...",NaN,35816620,2,"[javascript, documentation, jsdoc3]",JSDoc - How to document a limited number of va...,38
19,0,True,5,300,300,0,NaN,5,NaN,NaN,...,1457189381,https://stackoverflow.com/questions/35814892/n...,NaN,"{'reputation': 13, 'user_id': 3993279, 'user_t...",NaN,35814892,0,[sql],Need to resolve the query,330
20,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1475084934,https://stackoverflow.com/questions/35812015/a...,NaN,"{'reputation': 437, 'user_id': 5382318, 'user_...",NaN,35812015,2,"[android, api, detection, face-detection, face...",Android - Face Detection library not loading,1186
21,0,True,5,300,300,0,NaN,3,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35810045/p...,NaN,"{'reputation': 96, 'user_id': 5874937, 'user_t...",NaN,35810045,1,"[html, css]",Put input inside select,9256
22,0,True,5,300,300,0,NaN,9,NaN,NaN,...,1530529921,https://stackoverflow.com/questions/35813310/h...,NaN,"{'reputation': 583, 'user_id': 4336330, 'user_...",NaN,35813310,89,"[javascript, angular]",How to create timer in angular2,111341
23,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1457189441,https://stackoverflow.com/questions/35812676/h...,NaN,"{'reputation': 924, 'user_id': 6041389, 'user_...",NaN,35812676,0,"[php, css, wordpress, plugins, woocommerce]",How to remove bullet points from Woocommerce p...,799
24,0,True,5,300,300,0,35818791,1,NaN,NaN,...,1495541732,https://stackoverflow.com/questions/35818618/i...,NaN,"{'reputation': 337, 'user_id': 3993104, 'user_...",NaN,35818618,1,"[inno-setup, pascalscript]",Inno Setup - Conditionally hide/show static te...,505
25,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1517249492,https://stackoverflow.com/questions/35818780/d...,NaN,"{'reputation': 905, 'user_id': 1126393, 'user_...",NaN,35818780,3,"[c#, xaml, windows-10, win-universal-app]",Display data in a table in Universal App,4524
26,0,True,5,300,300,0,35841631,1,NaN,NaN,...,1457792500,https://stackoverflow.com/questions/35815834/s...,NaN,"{'reputation': 175, 'user_id': 1430637, 'user_...",NaN,35815834,2,"[smartcard, apdu]",smartcard select mf return 69 86 command not a...,1124
27,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35811574/c...,NaN,"{'reputation': 690, 'user_id': 3402493, 'user_...",NaN,35811574,1,"[azure, azure-sql-database, azure-mobile-servi...",Cannot create sql server database in Azure,1063
28,0,True,5,300,300,0,NaN,6,NaN,NaN,...,1457183028,https://stackoverflow.com/questions/35814097/r...,NaN,"{'reputation': 56, 'user_id': 3841982, 'user_t...",NaN,35814097,5,[regex],Regex to match beginning and end of a word wit...,8275
29,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1558420672,https://stackoverflow.com/questions/35810180/h...,NaN,"{'reputation': 754, 'user_id': 1791935, 'user_...",NaN,35810180,1,"[python, selenium, web-scraping, mechanize]",How to get buttons of all forms on webpage usi...,1524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,0,True,5,300,300,0,35836345,2,NaN,NaN,...,1495540415,https://stackoverflow.com/questions/35814080/v...,NaN,"{'reputation': 2216, 'user_id': 2632266, 'user...",NaN,35814080,5,"[elasticsearch, lucene]",Validation Failed: 1: mapping type is missing;...,15807
471,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35814745/d...,NaN,"{'reputation': 173, 'user_id': 5181038, 'user_...",NaN,35814745,2,"[c++, qt, cmake, clion]",Debug and executing QT project with cmake and ...,664
472,0,True,5,300,300,0,35818102,2,NaN,NaN,...,1457262100,https://stackoverflow.com/questions/35817908/f...,NaN,"{'reputation': 67, 'user_id': 6023047, 'user_t...",NaN,35817908,3,"[javascript, firefox, webrtc]",Firefox doesn&#39;t create an offer: Cannot cr...,1486
473,0,True,5,300,300,0,36115574,2,NaN,NaN,...,1457728881,https://stackoverflow.com/questions/35819616/h...,NaN,"{'reputation': 1825, 'user_id': 1139730, 'user...",NaN,35819616,1,"[ios, swift]",How to add list of songs with sections to UITa...,1098
474,0,True,5,300,300,0,NaN,4,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35811848/s...,NaN,"{'reputation': 6, 'user_id': 5422401, 'user_ty...",NaN,35811848,1,"[swift, multidimensional-array]",Swift 2 Using &quot;contains&quot; function wi...,956
475,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35814841/h...,NaN,"{'reputation': 2713, 'user_id': 116906, 'user_...",NaN,35814841,0,"[javascript, markdown, showdown]",How am I mis-calling showdown.Converter()?,74
476,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35821191/j...,NaN,"{'reputation': 105, 'user_id': 5966525, 'user_...",NaN,35821191,0,"[android, arrays, json, android-volley, jsonre...",JSON not returning anything in Volley,82
477,0,True,5,300,300,0,NaN,3,NaN,NaN,...,1457287443,https://stackoverflow.com/questions/35814255/d...,NaN,"{'reputation': 6, 'user_id': 6022221, 'user_ty...",NaN,35814255,1,"[webgl, openlayers-3]",Does OL3 support Vector Tiles on WebGL?,2081
478,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1478613479,https://stackoverflow.com/questions/35818958/h...,NaN,"{'reputation': 2259, 'user_id': 265650, 'user_...",NaN,35818958,4,[apache-kafka],How can we get Replication Factor and Retentio...,536
479,0,True,5,300,300,0,NaN,3,NaN,NaN,...,1457195307,https://stackoverflow.com/questions/35816602/a...,NaN,"{'reputation': 51, 'user_id': 5703925, 'user_t...",NaN,35816602,0,"[android, android-context]",Argument this doesn&#180;t work. [required: &#...,9406
480,0,True,5,300,300,0,35831528,2,NaN,NaN,...,1457192746,https://stackoverflow.com/questions/35815085/d...,NaN,"{'reputation': 15, 'user_id': 2573343, 'user_t...",NaN,35815085,0,"[c#, .net, asp.net-mvc-4, dependency-injection...",Dependency Registrar for other assembly,1852
481,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1457154583,https://stackoverflow.com/questions/35810285/t...,NaN,"{'reputation': 11, 'user_id': 4780883, 'user_t...",NaN,35810285,2,"[c#, asp.net, asp.net-mvc, entity-framework, c...",The specified cast from a materialized &#39;Sy...,1364
482,0,True,5,300,300,0,35811221,1,NaN,NaN,...,1478261284,https://stackoverflow.com/questions/35811053/u...,NaN,"{'reputation': 2183, 'user_id': 2194193, 'user...",NaN,35811053,11,"[c++, qt, c++11]",Using C++11 range-based for loop correctly in Qt,5975
483,0,True,5,300,300,0,38061331,3,NaN,NaN,...,1457298369,https://stackoverflow.com/questions/35818619/s...,NaN,"{'reputation': 4731, 'user_id': 2999675, 'user...",NaN,35818619,1,"[scala, apache-spark, apache-spark-sql]",(scala) Can not found registered table spark sql,2493
484,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1457319845,https://stackoverflow.com/questions/35809313/c...,NaN,"{'reputation': 46, 'user_id': 1220445, 'user_t...",NaN,35809313,0,"[ruby, savon, zuora]",Close AccountingPeriod in Zuora via SOAP,64
485,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35820437/i...,NaN,"{'reputation': 3720, 'user_id': 923846, 'user_...",NaN,35820437,2,"[parsing, intellij-idea, bnf, intellij-plugin,...",IntelliJ: Grammar-Kit / BNF: how to recover fr...,479
486,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35810831/c...,NaN,"{'reputation': 800, 'user_id': 2935014, 'user_...",NaN,35810831,0,"[php, curl, laravel-5]",cURL error 77 with Laravel 5 and XAMPP under W...,1363
487,0,True,5,300,300,0,NaN,2,NaN,NaN,...,1495541862,https://stackoverflow.com/questions/35819806/r...,NaN,"{'reputation': 14199, 'user_id': 284758, 'user...",NaN,35819806,18,"[rest, reactjs, redux, flux, hateoas]",REST (HATEOAS) and ReactJS,4599
488,0,True,5,300,300,0,NaN,0,NaN,NaN,...,1457219608,https://stackoverflow.com/questions/35818804/y...,NaN,"{'reputation': 71, 'user_id': 1848517, 'user_t...",NaN,35818804,0,"[php, api, rest, yii2]",Yii2 REST API Overlapping rate limits,211
489,0,True,5,300,300,0,40260250,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35809046/h...,NaN,"{'reputation': 35, 'user_id': 6020861, 'user_t...",NaN,35809046,6,"[git, git-merge, git-rebase]",How did these git commits get duplicated into ...,517
490,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35813895/b...,NaN,"{'reputation': 2396, 'user_id': 2559851, 'user...",NaN,35813895,1,"[rest, security, laravel]",Build a REST API available to authorized apps ...,61
491,0,True,5,300,300,0,40199716,1,NaN,NaN,...,1457372230,https://stackoverflow.com/questions/35819747/h...,NaN,"{'reputation': 79, 'user_id': 5049086, 'user_t...",NaN,35819747,0,"[java, sorting, hadoop, mapreduce, hadoop-part...",How to sort a column in data set in descending...,1483
492,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35811324/b...,NaN,"{'reputation': 771, 'user_id': 5345612, 'user_...",NaN,35811324,0,"[c, berkeley-db, ssd]",Berkeley DB store is so slow,108
493,0,True,5,300,300,0,35814121,2,NaN,NaN,...,1457181009,https://stackoverflow.com/questions/35814071/h...,NaN,"{'reputation': 489, 'user_id': 734388, 'user_t...",NaN,35814071,3,"[c#, ef-code-first, asp.net-core, entity-frame...",How to update entity framework 7 migrations an...,4938
494,0,True,5,300,300,0,NaN,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35819861/d...,NaN,"{'reputation': 1, 'user_id': 6023470, 'user_ty...",NaN,35819861,0,"[javascript, dojo, dgrid]",Dojo-Dgrid Dgrid tutoriel,159
495,0,True,5,300,300,0,35816093,2,NaN,NaN,...,1476796317,https://stackoverflow.com/questions/35814090/n...,NaN,"{'reputation': 375, 'user_id': 5821790, 'user_...",NaN,35814090,2,"[delphi, math, numbers, firemonkey, delphi-xe8]",Number Partition Algorithm Generator in Delphi...,173
496,0,True,5,300,300,0,36793501,4,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35820197/j...,NaN,"{'reputation': 45, 'user_id': 4387251, 'user_t...",NaN,35820197,3,"[javafx, jxbrowser]",JxBrowser HEAVYWEIGHT Dispose on WINDOW_CLOSE_...,952
497,0,True,5,300,300,0,35812810,1,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35812202/d...,NaN,"{'reputation': 1718, 'user_id': 3787777, 'user...",NaN,35812202,0,"[java, datainputstream]",Data Input Stream reads different than desired...,137
498,0,True,5,300,300,0,NaN,1,NaN,NaN,...,1476366310,https://stackoverflow.com/questions/35816002/a...,NaN,"{'reputation': 1, 'user_id': 6022637, 'user_ty...",NaN,35816002,0,"[automation, web]",Automate searches from Excel or CSV using Java...,140
499,0,True,5,300,300,0,NaN,0,NaN,NaN,...,NaN,https://stackoverflow.com/questions/35811888/h...,NaN,"{'reputation': 3191, 'user_id': 290284, 'user_...",NaN,35811888,4,"[android, maven, gradle, bintray, jcenter]",How long does it usually take bintray to sync ...,952

In [32]:
# Find items with a score of more than 5 and tagged 'Python'
top_python_items = expanded[(expanded['items_score'] >= 5) & ('python' in expanded['items_tags'])]
top_python_items_df = pd.DataFrame(top_python_items)
top_python_items_df

Empty DataFrame
Columns: [backoff, has_more, page, quota_max, quota_remaining, total, items_accepted_answer_id, items_answer_count, items_closed_date, items_closed_reason, items_creation_date, items_is_answered, items_last_activity_date, items_last_edit_date, items_link, items_migrated_from, items_owner, items_protected_date, items_question_id, items_score, items_tags, items_title, items_view_count]
Index: []

[0 rows x 23 columns]

In [1]:
expanded

NameError: name 'expanded' is not defined

In [41]:
[i for i in expanded['items_tags']for j in i if j == 'python']

[['python', 'binary-search-tree', 'doubly-linked-list'],
 ['python', 'python-2.7', 'flask', 'sqlalchemy', 'flask-sqlalchemy'],
 ['python', 'templates', 'flask', 'jinja2', 'pyinstaller'],
 ['python', 'image', 'search-engine'],
 ['python', 'selenium', 'web-scraping', 'mechanize'],
 ['python', 'shell', 'ssh', 'paramiko', 'interactive'],
 ['python', 'python-2.7', 'scrapy', 'scrapy-spider'],
 ['python', 'flask', 'python-3.5'],
 ['python', 'pandas'],
 ['python', 'string'],
 ['python', 'linux'],
 ['python', 'django', 'nginx'],
 ['python', 'python-multiprocessing'],
 ['python', 'websocket', 'python-3.5', 'channels', 'aiohttp'],
 ['python', 'lambda', 'pyqt'],
 ['python', 'django', 'django-forms', 'django-views'],
 ['python', 'decimal'],
 ['python', 'solaris', 'aix', 'su'],
 ['python', 'django', 'django-upgrade'],
 ['python', 'google-app-engine', 'mapreduce'],
 ['python', 'encryption', 'go', 'cryptography', 'aes'],
 ['python', 'django', 'django-queryset'],
 ['python', 'mongodb', 'mongodb-query', 'pymongo'],
 ['python', 'amazon-web-services', 'amazon-ec2', 'aws-lambda', 'boto3'],
 ['python', 'file', 'text', 'delimiter', 'cut']]

#### Question 3: Find the answers with id 6784 and 6473.

In [25]:
# your code here
#specific_ID = SITE.fetch('posts', ['items_accepted_answer_id'[6784, 6473]])
#specific_ans = expanded.items_accepted_answer_id[6784, 6473]

item_6784 = expanded[expanded['items_accepted_answer_id'] == 6784]
item_6473 = expanded[expanded['items_accepted_answer_id'] == 6473]

item_6784
item_6473

Empty DataFrame
Columns: [backoff, has_more, page, quota_max, quota_remaining, total, items_accepted_answer_id, items_answer_count, items_closed_date, items_closed_reason, items_creation_date, items_is_answered, items_last_activity_date, items_last_edit_date, items_link, items_migrated_from, items_owner, items_protected_date, items_question_id, items_score, items_tags, items_title, items_view_count]
Index: []

[0 rows x 23 columns]

In [2]:
class List(object):
    def count_spec_digits(self, integers_list, digits_list):
        # your code here
#        for i in digits_list:
#            count = integers_list.count(i)
        return [(i, integers_list.count(i)) for i in digits_list]

In [4]:
integers_list =  [112, 133, 243 ,3 ,1 ,2 ,3 ,4]
digits_list = [1, 8, 4]

In [7]:
integers_split = integers_list.split('')

AttributeError: 'list' object has no attribute 'split'